name: P-TA
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - transformers=4.35.0
  - tokenizers>=0.14,<0.15
  - pandas
  - scikit-learn
  - accelerate
  - datasets
  - pip
  - pip:
    - wandb 